### PR TITLE
Support no_proxy environment variable. #140

### PR DESCRIPTION
**Pull request by hgiddens**
Sorry if I've done any dumb stuff here. I tried to find a spec, and the nearest I could find was [some ancient info from W3C](http://www.w3.org/Daemon/User/Proxies/ProxyClients.html). I've thus implemented a subset of what other popular libraries support.

`no_proxy` contains a list of domain suffixes, separated by commas. The domain suffixes may optionally have leading periods; the commas may optionally have trailing spaces.

For example, if `no_proxy=internal.company.com, .other.company.com`, requests to `internal.company.com`, `foo.internal.company.com`, and `other.company.com` will avoid the proxy. Requests to `notactuallyinternal.company.com` will still go via the proxy.

###### Domain suffix vs. string suffix
wget and Python's urllib3 avoid the proxy if one of the `no_proxy` hosts is a string suffix of the request host, rather than a domain suffix (with special casing so `no_proxy=.foo.example` avoids the proxy for requests to `foo.example`).

###### Ignoring case/spaces
Some implementations ignore all spaces, rather than just `0x20`s following a comma. Some implementations also use case-sensitive domain handling.

###### Port-specific rules
Ruby's stdlib implementation can be made to apply only to specific ports.

###### Avoiding the proxy for CADR ranges
Python's urllib3 allows you to specify e.g. `no_proxy=internal.company.com,192.168.0.0/16`.

###### Avoiding the proxy for all requests
Ruby and cURL avoid the proxy for all requests if `no_proxy=*` is set.

### CODE REVIEW

**Comment by snoyberg** [comment]
Unless I'm misreading this, this code will require parsing the `no_proxy` environment variable from scratch on each request. It would be better to explicitly parse it immediately into some intermediate data structure, and then perform lookups on that.

**Comment by hgiddens** [comment]
Yeah, you're quite right. Would `newManager` be an appropriate place for the parsing step?

**Comment by snoyberg** [comment]
It's fine to do it in this function. Just do it outside of the inner function (in the same part of the code where `getEnvironment` is called).

**Comment by hgiddens** [comment]
Is there anything else you'd like done on this one?

**Comment by snoyberg** [comment]
I'll check now. For future reference: Github doesn't send notifications on new commits to a PR, so it's good to add a comment when making such a change.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
