### PR TITLE
Allow creating a TLS-based Manager using specified settings

### LINKED ISSUE #278: newTlsManager with provided settings
It would be nice to have a variant of `newTlsManager` that uses a provided `ManagerSettings` as a base rather than the default one so that things like timeouts can be configured.

I can provide a PR if you prefer.

### PR DESCRIPTION
**Pull request by ivan-m**
For example, to allow for a different timeout.

Closes #278

### CODE REVIEW

**Comment by snoyberg** [comment]
Can you do a minor version bump, update the ChangeLog, and add a `@since` comment?

**Comment by ivan-m** [comment]
Sure. Is there any other functions I should similarly generalise whilst I'm at it?

**Comment by snoyberg** [comment]
None that I can think of.

**Comment by ivan-m** [comment]
Done

**Comment by ivan-m** [comment]
Is it possible for a release to be made with this please?

**Comment by snoyberg** [comment]
Thanks for the ping, done.

**Comment by ivan-m** [comment]
By "done", do you mean up on Hackage/Stackage? Because I'm still not seeing it there...

**Comment by snoyberg** [comment]
My mistake, I'd uploaded http-client instead of http-client-tls. Should be
good now.

**Pull request merged**
