### PR TITLE
history not being fully fetched

### PR DESCRIPTION
**Pull request by mwotton**

### CODE REVIEW

**Comment by snoyberg** [comment]
Can you clarify what this PR is addressing?

**Comment by mwotton** [comment]
apologies, I pushed this then realised the mistake I'd made - I thought I couldn't grab the full response from the history, but I'd called responseBody on it rather than brConsume, so i was only getting the first chunk. Meant to delete it when I realised but hadn't quite got round to it.

**Comment by snoyberg** [comment]
Got it, thanks for clarifying :)

**Comment by mwotton** [comment]
thanks for http-client, btw, it's made my life a lot easier:)

**Pull request closed without merging**
