### PR TITLE
Support proxy for openssl

### PR DESCRIPTION
**Pull request by junjihashimoto**
Hi,

This PR supports http-proxy for openssl.
The test-flag(test-proxy of cabal)  is off by default.

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks! I'm assuming you've actually run the tests against a local proxy, correct?

Could you add a minor version bump in the cabal file and make a note in the ChangeLog?

**Comment by junjihashimoto** [comment]
I run following tests.
At first, lauch http-proxy by node.
The proxy-code is [http-proxy-server-in-80-lines.js](http://qiita.com/LightSpeedC/items/5c1edc2c974206c743f4).
(I think apache-proxy is better than node's one.)
Then, run stack-test.

```
$ stack test --flag http-client-openssl:test-proxy
http-client-openssl-0.2.1.0: test (suite: spec)


make a TLS connection
make a TLS connection with proxy

Finished in 1.4285 seconds
2 examples, 0 failures
```

I've update version and changelog.

**Comment by snoyberg** [comment]
Thanks!

**Comment by junjihashimoto** [comment]
Thank you, too!

**Pull request merged**
