### PR TITLE
Update module comment to 'checkResponse'.

### PR DESCRIPTION
**Pull request by seagreen**

### CODE REVIEW

**Comment by seagreen** [comment]
Not sure if one word fixes are worth the trouble, let me know if not.

**Comment by snoyberg** [comment]
The fix is definitely appreciated! However, this points out that the entire previous sentence is in fact wrong: the default is no longer to throw exceptions, and therefore `checkResponse` doesn't even need to be mentioned. Would you be able to update the PR to just remove the now-incorrect phrase?

**Comment by seagreen** [comment]
No wonder I was confused, I had the changelog open and was trying to resolve that paragraph with what I thought had changed:)

Paragraph removed; commit amended and force pushed.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
