### PR TITLE
Fix code and remove old imports

### PR DESCRIPTION
**Pull request by psibi**
Data.Conduit.Binary isn't present anymore. Using sinkFile from
conduit-combinators package.

The patched code works.

### CODE REVIEW

**Comment by snoyberg** [comment]
Data.Conduit.Binary is still available from conduit-extra.

**Comment by psibi** [comment]
Oops! Sorry, didn't know that. I think probably it can be mentioned in the documentation to install conduit-extra for that example ?

**Comment by snoyberg** [comment]
Sure. Want to update the PR?

**Comment by psibi** [comment]
Thanks, removed the original commit and updated with a new one.

**Comment by snoyberg** [comment]
Great!

**Pull request merged**
