### PR TITLE
expose Network.HTTP.Client.Types

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**

### CODE REVIEW

**Comment by snoyberg** [comment]
There's no motivation provided for doing this, and there's plenty of motivation not to do this.

**Comment by BebeSparkelSparkel** [comment]
It would be very nice to have access to the Request and Response constructors to make convenience functions. Would you be open to exposing those?

**Comment by snoyberg** [comment]
These are already exposed in the `.Internal` module: https://www.stackage.org/haddock/nightly-2020-03-26/http-client-0.6.4.1/Network-HTTP-Client-Internal.html#t:Request

**Comment by BebeSparkelSparkel** [comment]
Thanks

**Pull request closed without merging**
